GET_TABLES = """
SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_SCHEMA, TABLE_NAME
"""

GET_COLUMNS = """
SELECT
    TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME,
    DATA_TYPE, CHARACTER_MAXIMUM_LENGTH,
    CASE WHEN IS_NULLABLE = 'YES' THEN 1 ELSE 0 END AS IS_NULLABLE,
    COLUMN_DEFAULT, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION
"""

GET_PRIMARY_KEYS = """
SELECT tc.TABLE_SCHEMA, tc.TABLE_NAME, kcu.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
    ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
    AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY tc.TABLE_SCHEMA, tc.TABLE_NAME, kcu.ORDINAL_POSITION
"""

GET_FOREIGN_KEYS = """
SELECT
    fk.TABLE_SCHEMA, fk.TABLE_NAME, fk.COLUMN_NAME,
    pk.TABLE_SCHEMA AS REF_SCHEMA,
    pk.TABLE_NAME   AS REF_TABLE,
    pk.COLUMN_NAME  AS REF_COLUMN
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE fk
    ON rc.CONSTRAINT_NAME = fk.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE pk
    ON rc.UNIQUE_CONSTRAINT_NAME = pk.CONSTRAINT_NAME
    AND fk.ORDINAL_POSITION = pk.ORDINAL_POSITION
ORDER BY fk.TABLE_SCHEMA, fk.TABLE_NAME, fk.ORDINAL_POSITION
"""

GET_INDEXES = """
SELECT
    s.name AS SCHEMA_NAME,
    t.name AS TABLE_NAME,
    i.name AS INDEX_NAME,
    CAST(i.is_unique AS INT),
    CAST(i.is_primary_key AS INT),
    STRING_AGG(c.name, ',') WITHIN GROUP (ORDER BY ic.key_ordinal) AS COLS
FROM sys.indexes i
JOIN sys.tables t  ON i.object_id = t.object_id
JOIN sys.schemas s ON t.schema_id = s.schema_id
JOIN sys.index_columns ic
    ON i.object_id = ic.object_id AND i.index_id = ic.index_id
JOIN sys.columns c
    ON ic.object_id = c.object_id AND ic.column_id = c.column_id
WHERE i.name IS NOT NULL AND ic.is_included_column = 0
GROUP BY s.name, t.name, i.name, i.is_unique, i.is_primary_key
ORDER BY s.name, t.name, i.name
"""

GET_OBJECTS = """
SELECT ROUTINE_SCHEMA, ROUTINE_NAME, ROUTINE_TYPE
FROM INFORMATION_SCHEMA.ROUTINES
UNION ALL
SELECT TABLE_SCHEMA, TABLE_NAME, 'VIEW'
FROM INFORMATION_SCHEMA.VIEWS
ORDER BY 1, 2, 3
"""
